# Generated by Django 5.2.7 on 2025-10-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Sinf nomi')),
            ],
            options={
                'verbose_name': 'Sinf nomi',
                'verbose_name_plural': 'Sinflar nomi',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_full_name', models.CharField(max_length=512, verbose_name='Rahmarni toliq ismi')),
                ('class_teacher_tg_id', models.CharField(max_length=156, verbose_name='Rahbarni telegram idsi')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.classname', verbose_name='Sing nomi')),
            ],
        ),
    ]
