# Generated by Django 5.2.7 on 2025-10-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_sababi_alter_student_status'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Sinf', 'verbose_name_plural': 'Sinflar'},
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='students.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.classname', verbose_name='Sinf nomi'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_teacher_full_name',
            field=models.CharField(max_length=512, verbose_name='Rahbarni toliq ismi'),
        ),
    ]
