# Generated by Django 5.2.7 on 2025-10-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_class_options_class_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.classname', unique=True, verbose_name='Sinf nomi'),
        ),
    ]
