# Generated by Django 5.2.7 on 2025-10-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sababi',
            field=models.TextField(blank=True, verbose_name='Sababi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='Bor', verbose_name='Statusi'),
        ),
    ]
