# Generated by Django 5.2.7 on 2025-10-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_class_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.classname', verbose_name='Sinf nomi'),
        ),
    ]
