# Generated by Django 5.2.7 on 2025-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_class_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_teacher_full_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Rahbarni toliq ismi'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_teacher_tg_id',
            field=models.CharField(blank=True, max_length=156, null=True, verbose_name='Rahbarni telegram idsi'),
        ),
    ]
