# Generated by Django 5.2.7 on 2025-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_class_class_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='this_updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
