# Generated by Django 5.2.7 on 2025-10-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_class_this_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='this_updated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yangilanganmi'),
        ),
    ]
