# Generated by Django 5.2.7 on 2025-10-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1024, verbose_name="O'quvchining toliq ismi")),
                ('status', models.CharField(default='Bor', verbose_name='Kelganmi')),
                ('sababi', models.TextField(verbose_name='Sababi')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.class', verbose_name='Sinfi')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
    ]
