# Generated by Django 5.2.7 on 2025-10-20 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Admin',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin ', 'verbose_name_plural': 'Adminlar '},
        ),
    ]
